version: '3.8'

services:
  server:
    build:
      context: ./Backend   # Path to the directory containing server code and Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - react

  react:
    build:
      context: ./frontend    # Path to the directory containing React code and Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
